//! MB88xx single-step validation against generated vectors.
//!
//! What this does and does not establish is worth stating, because the vectors
//! are produced by the same CPU they are replayed against. Regenerate them and
//! replay them in one sitting and almost every assertion here is a tautology.
//! Two things save it:
//!
//! - `cpu-validation/test_data/` is gitignored but persists locally, so a
//!   working copy replays vectors generated by *earlier* code. That is the
//!   regression gate, and it is why the suite is worth running after a CPU
//!   change rather than only after regenerating.
//! - The machine-cycle count is checked against the generator's hand-written
//!   1-versus-2-cycle instruction table rather than against the CPU. That
//!   comparison is between two independent statements about the part and can
//!   fail even on freshly generated vectors.
//!
//! The oracle proper is the C++ cross-validator
//! (`cross-validation/bin/validate_mb88xx`), which runs an unrelated core over
//! the same files. This is the cheap gate, not a replacement for it.

use phosphor_core::cpu::mb88xx::{Mb88xx, Mb88xxVariant};
use phosphor_cpu_validation::{Mb88xxTestCase, Mismatches};

/// The generator emits MB8841 vectors: 2048-byte ROM, 128-nibble RAM, 5-bit PA.
const VARIANT: Mb88xxVariant = Mb88xxVariant::Mb8841;

/// Two machine cycles is the longest instruction the part has. A run that gets
/// past this is a CPU that never returned to an instruction boundary, not a
/// slow instruction, so stop and let the cycle-count check report it.
const MAX_CYCLES: usize = 8;

// Index meanings in a vector's `io` array. These are the on-disk format, fixed
// by what `gen_mb88xx_tests::build_io` writes, not a choice this file makes.
const IO_K: u8 = 0;
const IO_O: u8 = 1;
const IO_P: u8 = 2;
const IO_R0: u8 = 3;
const IO_R3: u8 = 6;
const IO_SI: u8 = 7;

/// Build a CPU in the vector's initial state.
fn load(tc: &Mb88xxTestCase) -> Mb88xx {
    let s = &tc.initial;
    let mut cpu = Mb88xx::new(VARIANT);

    cpu.pc = s.pc;
    cpu.pa = s.pa;
    cpu.a = s.a;
    cpu.x = s.x;
    cpu.y = s.y;
    cpu.si = s.si;
    cpu.st = s.st;
    cpu.zf = s.zf;
    cpu.cf = s.cf;
    cpu.vf = s.vf;
    cpu.sf = s.sf;
    // The vector calls it `nf`; the CPU models it as the /INT pin level.
    cpu.irq_pin = s.nf;
    cpu.pio = s.pio;
    cpu.th = s.th;
    cpu.tl = s.tl;
    cpu.tp = s.tp;
    cpu.sb = s.sb;
    cpu.stack = s.stack;

    // ROM is sparse: the generator randomizes all 2KB but records only the
    // addresses the instruction under test reads. Anything else stays zero,
    // which is correct precisely as long as the instruction reads nothing else.
    for &(addr, val) in &s.rom {
        cpu.poke_rom(addr, val);
    }
    for &(addr, val) in &s.ram {
        cpu.poke_ram(addr, val);
    }
    for &(port, val) in &s.io {
        set_io(&mut cpu, port, val);
    }

    cpu
}

/// Apply one entry of a vector's `io` array.
///
/// `r_output` and `o_latch` are deliberately absent from the format and so are
/// left at their reset values: no instruction reads either one back (SETR,
/// RSTR, SETD and RSTD all read `r_input` and write `r_output`), and `o_latch`
/// reaches an instruction only through the `dynamic_k` path, which generated
/// vectors never enable.
fn set_io(cpu: &mut Mb88xx, port: u8, val: u8) {
    match port {
        IO_K => cpu.k_input = val,
        // What `read_o` returns is the shared external register, which OUTO
        // writes through the PLA, not the internal latch.
        IO_O => cpu.port_o = val,
        IO_P => cpu.p_output = val,
        IO_R0..=IO_R3 => cpu.r_input[(port - IO_R0) as usize] = val,
        IO_SI => cpu.si_input = val,
        other => panic!("vector names I/O port {other}, which the format does not define"),
    }
}

/// The port values a vector's `io` array records, read back off a live CPU.
fn io_snapshot(cpu: &Mb88xx) -> Vec<(u8, u8)> {
    let mut io = vec![
        (IO_K, cpu.k_input),
        (IO_O, cpu.read_o()),
        (IO_P, cpu.read_p()),
    ];
    for i in 0..4u8 {
        io.push((IO_R0 + i, cpu.r_input[i as usize]));
    }
    io.push((IO_SI, cpu.si_input));
    io
}

fn run_case(tc: &Mb88xxTestCase) -> Option<String> {
    let mut cpu = load(tc);
    let mut m = Mismatches::default();

    // Run to the next instruction boundary and count, rather than calling
    // execute_cycle() the number of times the vector says. Replaying the
    // recorded count would assert nothing; measuring it compares the CPU's own
    // idea of when an instruction ends against the generator's separate table
    // of which opcodes take two cycles. This is the assertion in this file that
    // can fail on same-session vectors.
    let mut cycles = 0;
    while cycles < MAX_CYCLES {
        cpu.execute_cycle();
        cycles += 1;
        if cpu.at_instruction_boundary() {
            break;
        }
    }
    m.check(cycles, tc.cycles, format_args!("machine cycles"));

    let f = &tc.final_state;
    m.check(cpu.pc, f.pc, format_args!("PC"));
    m.check(cpu.pa, f.pa, format_args!("PA"));
    m.check(cpu.a, f.a, format_args!("A"));
    m.check(cpu.x, f.x, format_args!("X"));
    m.check(cpu.y, f.y, format_args!("Y"));
    m.check(cpu.si, f.si, format_args!("SI"));
    m.check(cpu.st, f.st, format_args!("ST"));
    m.check(cpu.zf, f.zf, format_args!("ZF"));
    m.check(cpu.cf, f.cf, format_args!("CF"));
    m.check(cpu.vf, f.vf, format_args!("VF"));
    m.check(cpu.sf, f.sf, format_args!("SF"));
    m.check(cpu.irq_pin, f.nf, format_args!("NF"));
    m.check(cpu.pio, f.pio, format_args!("PIO"));
    m.check(cpu.th, f.th, format_args!("TH"));
    m.check(cpu.tl, f.tl, format_args!("TL"));
    m.check(cpu.tp, f.tp, format_args!("TP"));
    m.check(cpu.sb, f.sb, format_args!("SB"));
    m.check(cpu.stack, f.stack, format_args!("stack"));

    for &(addr, expected) in &f.ram {
        m.check(
            cpu.peek_ram(addr),
            expected,
            format_args!("RAM[0x{addr:02X}]"),
        );
    }
    // ROM is read-only, so this catches a write that escaped into program space
    // rather than a computed value.
    for &(addr, expected) in &f.rom {
        m.check(
            cpu.peek_rom(addr),
            expected,
            format_args!("ROM[0x{addr:03X}]"),
        );
    }

    let actual_io = io_snapshot(&cpu);
    for &(port, expected) in &f.io {
        let actual = actual_io.iter().find(|(p, _)| *p == port).map(|(_, v)| *v);
        m.check(actual, Some(expected), format_args!("IO[{port}]"));
    }

    m.into_report(&tc.name)
}

#[test]
fn test_all_opcodes() {
    phosphor_cpu_validation::run_vector_suite::<Mb88xxTestCase, _>(
        "mb88xx",
        "run: cargo run -p phosphor-cpu-validation --bin gen_mb88xx_tests -- all",
        run_case,
    );
}
