//! Asteroids Deluxe (1980) discrete sound, built on the [`DiscreteCircuit`]
//! framework.
//!
//! Two effect paths, thrust and explosion, and nothing else: the POKEY at M7/8
//! makes every other sound on this board, which is what the drawing says in so
//! many words ("The Custom Audio chip M7/8 generates most of the sounds for
//! Asteroids Deluxe"). Those two are the ones it does not make, and they are
//! built here.
//!
//! # Schematics
//!
//! | Drawing | Source | Pages |
//! |---|---|---|
//! | `OUTPUTS`, sheet 2 side B, `Asteroids Deluxe Cabaret` drawing package supplement | `arcade-museum.com/manuals-videogames/A/AstDlx-Cabaret-sp.pdf` | PDF p7, read |
//! | `Sheet 1, Side B` memory map, same package | same | PDF p4, read |
//!
//! The memory map is the authority for the three write addresses: 0x3600 is
//! `Explosion pitch` on D7-D6 and `Explosion volume` on D5-D2, 0x3C03 is
//! `Ship thrust sound`, and 0x3E00 is `Noise generator reset`. All three were
//! being discarded before this existed.
//!
//! # Shape of it
//!
//! ```text
//!   12 kHz -> R8,P8 LS164 x2 --+--> 4016 R11 (SHPTHRUSTEN) -> R154/C116
//!   NOISERESET -> pin 9 clear  |      -> R155/R160/R157 band-pass
//!                              |      -> R161/R159 low-pass -> SHPSND -> R158
//!                              |
//!                              +--> LS74 P,R27 sample and hold
//!                                     clocked by D5 NOR(12 kHz, P7 ripple)
//!                                     -> x R6 DAC (EXPAUD0-3) -> EXPLOSND -> R85
//!
//!   0x3600 -> F6 LS174 -+-> EXPAUD0-3 (DB5-DB2)  -> R6
//!                       +-> EXPITCH0-1 (DB6,DB7) -> P7 9316 load inputs
//!   0x3C03 -> M10 LS259 Q3 -> SHPTHRUSTEN
//!   0x3E00 -> NOISERESET
//! ```
//!
//! **There is one noise generator, not two.** R8 and P8 make a single sixteen-bit
//! register and the NOISE net leaving N4 goes to both paths: thrust takes it
//! continuously through the 4016, and the explosion samples it with the LS74 at
//! a rate P7 divides down. That is the structural fact worth stating, because
//! modeling the explosion as its own slowly-clocked register sounds nearly the
//! same and quietly decorrelates two things the board has sharing a source.
//!
//! # This board's circuit, not Asteroids' with five paths switched off
//!
//! The two boards' thrust and explosion are the same circuit, part for part,
//! under different designators. That makes it tempting to reuse
//! [`crate::asteroids_sound`], and this does not, for two reasons.
//!
//! The mixer differs. On Asteroids thrust and explosion enter the summing node
//! through the same resistor and are weighted equally. Here they do not:
//! explosion enters through R85 4.7k and thrust through R158 3.3k, so this board
//! asks for thrust 1.42 times louder relative to the explosion. The POKEY enters
//! the same node through R69 100k, so the circuit's output has to be mixed with
//! a chip rather than being the whole of what the speaker hears.
//!
//! And the parts that file still carries as reference-netlist literals are read
//! off the drawing here instead: the explosion's pitch divider is the four gates
//! on P7's load inputs rather than a table of four numbers, its volume is R6's
//! four preferred values rather than a linear fraction, and its noise is sampled
//! from the shared register rather than generated by a private one. Anyone
//! merging the two later should merge toward this one.

use phosphor_core::core::debug::{DebugRegister, Debuggable};
use phosphor_core::core::save_state::{SaveError, StateReader, StateWriter};
use phosphor_core::device::{
    CustomComponent, DataInputId, DiscreteCircuit, DiscreteCircuitBuilder, LfsrOutput, LfsrShift,
    LfsrSpec, LogicInputId, NodeId, OutputGain, PulseInputId,
};
use phosphor_macros::Saveable;

// ---------------------------------------------------------------------------
// The noise generator, which both paths share
// ---------------------------------------------------------------------------

/// Rate the whole sound section is clocked at: the 12 kHz off the divider chain.
const NOISE_CLOCK_HZ: f64 = 12_000.0;

/// R8 and P8, two LS164s cascaded into one sixteen-bit shift register.
///
/// Read off the drawing rather than assumed: R8's QH goes to P8's A and B, so
/// the two are one register of sixteen; both are clocked from the same 12 kHz
/// and both are cleared by NOISERESET on pin 9. The feedback taps are R8's QG,
/// bit seven of the chain, and P8's QG, bit fifteen. P4 (LS86) exclusive-ORs
/// them and N4 (LS00), with its inputs tied together as an inverter, makes that
/// an XNOR.
///
/// Two consequences of reading it this way rather than as "a noise source".
/// N4's output is both the feedback into R8 and the NOISE net itself, so what
/// the rest of the board hears is the gate's own term and not a register bit.
/// And an XNOR makes the all-zero state ordinary rather than a lock, which is
/// what lets NOISERESET clear the registers and have the thing carry on: with
/// an XOR that clear would have stopped it dead.
const NOISE_LFSR: LfsrSpec = LfsrSpec {
    width: 16,
    taps: (6, 14),
    seed: 0,
    shift: LfsrShift::TowardHigh,
    invert_feedback: true,
    output: LfsrOutput::Feedback,
};

// ---------------------------------------------------------------------------
// The explosion's pitch, from the gates that set it
// ---------------------------------------------------------------------------

/// How many 12 kHz counts the explosion holds each noise sample for.
///
/// P7 is a 9316 with its RIP taken back through the L4 inverter to LD, so at
/// terminal count it reloads A-D and divides the 12 kHz by `16 - N`. Its count
/// enables CT and CP are both tied high, so it never pauses. What sits on the
/// four load inputs is the two latched pitch bits and two gates:
///
/// | Load input | Signal |
/// |---|---|
/// | A, pin 3 | EXPITCH1 |
/// | B, pin 4 | EXPITCH0 |
/// | C, pin 5 | EXPITCH0 inverted, through L4 |
/// | D, pin 6 | EXPITCH1 OR EXPITCH0, through N5 |
///
/// Written out as the dividers those produce it reads 12, 6, 3, 5, which is not
/// monotonic and looks like an arbitrary table when it is written as one. It is
/// four gates, and the code below is them rather than the table they make.
fn explosion_divider(reg: u8) -> f64 {
    // The two pitch bits as F6 latches them: DB7 to 6D, DB6 to 1D.
    let pitch1 = reg & 0x80 != 0;
    let pitch0 = reg & 0x40 != 0;
    let load = u32::from(pitch1)
        | u32::from(pitch0) << 1
        | u32::from(!pitch0) << 2
        | u32::from(pitch1 || pitch0) << 3;
    f64::from(16 - load)
}

// ---------------------------------------------------------------------------
// The noise generator and the explosion's sample-and-hold, both on the
// framework's custom escape hatch
// ---------------------------------------------------------------------------

/// R8, P8, P4 and N4 as one component, because NOISERESET clears them.
///
/// The framework's own LFSR node has no reset input, and this board has a
/// `Noise generator reset` strobe at 0x3E00 wired to pin 9 of both LS164s. That
/// is the whole reason this rides the `Custom` escape hatch instead: a shared
/// primitive that cannot be cleared would leave the strobe doing nothing, which
/// is the state this board was already in.
///
/// Input: `[noise_reset 0/1]`. Output: N4's term, +1 or -1.
struct NoiseGenerator {
    shift: u16,
    clock_acc: f64,
    out: f64,
}

impl NoiseGenerator {
    fn new() -> Self {
        Self {
            shift: 0,
            clock_acc: 0.0,
            out: -1.0,
        }
    }

    /// One 12 kHz clock edge: P4 exclusive-ORs the two taps, N4 inverts, and the
    /// result shifts in at R8's A and B while being the NOISE net itself.
    fn clock(&mut self) {
        let (a, b) = NOISE_LFSR.taps;
        let feedback = !(((self.shift >> a) ^ (self.shift >> b)) & 1) & 1;
        self.shift = (self.shift << 1) | feedback;
        self.out = if feedback != 0 { 1.0 } else { -1.0 };
    }
}

impl CustomComponent for NoiseGenerator {
    fn reset(&mut self) {
        self.shift = 0;
        self.clock_acc = 0.0;
        self.out = -1.0;
    }

    fn step(&mut self, inputs: &[f64], dt: f64) -> f64 {
        if inputs[0] > 0.5 {
            // Pin 9 on both registers. An XNOR chain runs perfectly well out of
            // all-zeroes, which is what makes this a reset rather than a stall.
            self.shift = 0;
        }
        self.clock_acc += NOISE_CLOCK_HZ * dt;
        while self.clock_acc >= 1.0 {
            self.clock_acc -= 1.0;
            self.clock();
        }
        self.out
    }

    fn save_state(&self, w: &mut StateWriter) {
        w.write_u16_le(self.shift);
        w.write_f64_le(self.clock_acc);
        w.write_f64_le(self.out);
    }

    fn load_state(&mut self, r: &mut StateReader) -> Result<(), SaveError> {
        self.shift = r.read_u16_le()?;
        self.clock_acc = r.read_f64_le()?;
        self.out = r.read_f64_le()?;
        Ok(())
    }
}

/// The LS74 at P,R27 that samples NOISE for the explosion.
///
/// This is the structural difference between the explosion and the thrust, and
/// it is why the two cannot simply be two noise sources. There is one noise
/// generator on this board. Thrust takes it continuously through the 4016, and
/// the explosion **samples** it: the LS74's clock is D5 (LS02) NORing the 12 kHz
/// against P7's ripple carry, which is one narrow pulse per counter cycle, and
/// the flip-flop holds whatever NOISE was doing at that instant until the next
/// one. Slowing that clock is what drops the explosion's pitch.
///
/// A register clocked slowly would give a similar-sounding stair-step, and that
/// is the shortcut worth naming: it would decorrelate the explosion from the
/// thrust, where the board has them share a generator.
///
/// Inputs: `[noise, sample rate in Hz]`.
struct ExplosionSampleHold {
    held: f64,
    clock_acc: f64,
}

impl ExplosionSampleHold {
    fn new() -> Self {
        Self {
            held: 0.0,
            clock_acc: 0.0,
        }
    }
}

impl CustomComponent for ExplosionSampleHold {
    fn reset(&mut self) {
        self.held = 0.0;
        self.clock_acc = 0.0;
    }

    fn step(&mut self, inputs: &[f64], dt: f64) -> f64 {
        let noise = inputs[0];
        let rate = inputs[1].max(1.0);
        self.clock_acc += rate * dt;
        while self.clock_acc >= 1.0 {
            self.clock_acc -= 1.0;
            self.held = noise;
        }
        self.held
    }

    fn save_state(&self, w: &mut StateWriter) {
        w.write_f64_le(self.held);
        w.write_f64_le(self.clock_acc);
    }

    fn load_state(&mut self, r: &mut StateReader) -> Result<(), SaveError> {
        self.held = r.read_f64_le()?;
        self.clock_acc = r.read_f64_le()?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// The explosion's volume DAC: R6
// ---------------------------------------------------------------------------

/// The four resistors of R6, most significant first.
///
/// EXPAUD0 is DB5 and drives the smallest resistor, so it is the top bit. These
/// are **not** a binary ladder: a true one would be 5.6k, 11.2k, 22.4k and
/// 44.8k, and the board uses the nearest preferred values instead. The top bit
/// is worth 0.5435 of full scale where a binary ladder would make it 0.5333, so
/// the steps are slightly uneven, and modeling this as `code / 15` would smooth
/// out a wobble the hardware really has.
const R6_OHMS: [f64; 4] = [5_600.0, 12_000.0, 22_000.0, 47_000.0]; // R41, R44, R42, R43

/// R6's per-bit weights, bit 0 first, normalized so all four on is full scale.
fn r6_weights() -> Vec<f64> {
    let total: f64 = R6_OHMS.iter().map(|r| 1.0 / r).sum();
    // Bit 0 of the code is EXPAUD3, the largest resistor, so the array reverses.
    R6_OHMS.iter().rev().map(|r| 1.0 / (r * total)).collect()
}

// ---------------------------------------------------------------------------
// The summing node at P11, and the one number in this file that is not on it
// ---------------------------------------------------------------------------

/// Explosion into the P11 summing node: R85.
const R_EXPLOSION: f64 = 4_700.0;

/// Thrust into the P11 summing node: R158. Note it is *lower* than the
/// explosion's, so the board wants thrust the louder of the two.
const R_THRUST: f64 = 3_300.0;

/// The POKEY's AUD pin into the P11 summing node: R69.
///
/// Its own node also carries R67 10k pulling up to +5 V and C30 0.015 uF to
/// ground, which is a pole near a kilohertz on the chip's output. Neither is
/// modeled here: this file owns the two discrete paths, and the chip's own
/// output network belongs with the chip.
const R_POKEY: f64 = 100_000.0;

/// How far the discrete stages swing against the POKEY's AUD pin.
///
/// **This is the one fitted number in this file, and it is the only thing
/// between here and a mix derived entirely from the drawing.** The three
/// summing resistors give the three weights, but a weight multiplies a voltage,
/// and the two kinds of source arrive at very different sizes: the POKEY's AUD
/// pin is a current output sitting on a 10k pull-up, and the discrete paths are
/// LM324 outputs. Their ratio is not on any sheet.
///
/// That the resistors differ by more than twenty to one is itself the evidence
/// that they are compensating for exactly this: a designer summing three
/// equal-sized signals does not reach for 3.3k, 4.7k and 100k. So the resistors
/// alone cannot be used, and the alternative of ignoring them and picking three
/// levels by ear would throw away the part that *is* documented.
///
/// To retire it, express both sides in volts: the POKEY's AUD current into its
/// load, and the discrete paths' rails through their output stages. That is the
/// same open question [`crate::asteroids_sound`] records for its own mixer, and
/// it should be answered for both boards at once.
const DISCRETE_SWING_OVER_POKEY: f64 = 0.03;

/// The three mixer shares, normalized so a full-scale everything cannot clip.
///
/// Conductance times swing, which is what an inverting summing amplifier does.
/// The feedback resistor R86 10k is common to all three and cancels out of the
/// ratio, so it does not appear.
const fn mix_shares() -> (f64, f64, f64) {
    let pokey = 1.0 / R_POKEY;
    let explosion = DISCRETE_SWING_OVER_POKEY / R_EXPLOSION;
    let thrust = DISCRETE_SWING_OVER_POKEY / R_THRUST;
    let total = pokey + explosion + thrust;
    (pokey / total, explosion / total, thrust / total)
}

/// The POKEY's share of the summing node, for the board to weight its samples
/// by. The two discrete paths carry their own shares inside the circuit.
pub const POKEY_MIX_SHARE: f64 = mix_shares().0;

// ---------------------------------------------------------------------------
// Thrust chain, from sheet 2 side B
// ---------------------------------------------------------------------------

/// R154 and C116: the pole in front of the band-pass.
const THRUST_RC_R: f64 = 2_200.0;
const THRUST_RC_C: f64 = 1e-6;

/// The multiple-feedback band-pass around one section of the LM324 at P11:
/// R155 in, R160 to the +5 V reference, R157 across, C118 and C120.
const THRUST_BP_R_IN: f64 = 47_000.0; // R155
const THRUST_BP_R_REF: f64 = 1_200.0; // R160
const THRUST_BP_RF: f64 = 270_000.0; // R157
const THRUST_BP_C: f64 = 0.1e-6; // C118 and C120

/// Center gain of that band-pass, which its own shape fixes.
const THRUST_BP_CENTER_GAIN: f64 = THRUST_BP_RF / (2.0 * THRUST_BP_R_IN);

/// Q of the band-pass, and so the factor by which it concentrates the noise's
/// energy at its center. Both boards' chain is the same, so this is the same
/// 7.6 [`crate::asteroids_sound`] uses.
const THRUST_Q: f64 = 7.6;

/// The active low-pass after it: R161 in, R159 across, C119.
const THRUST_LP_R_IN: f64 = 6_800.0; // R161
const THRUST_LP_RF: f64 = 10_000.0; // R159
const THRUST_LP_C: f64 = 0.1e-6; // C119
const THRUST_LP_GAIN: f64 = THRUST_LP_RF / THRUST_LP_R_IN;

// ---------------------------------------------------------------------------
// Explosion chain, from sheet 2 side B
// ---------------------------------------------------------------------------

/// The RC on the explosion's output, matching the Asteroids path it is lifted
/// from.
const EXPLOSION_RC_R: f64 = 3_042.0;
const EXPLOSION_RC_C: f64 = 1e-6;

// ---------------------------------------------------------------------------
// Circuit construction
// ---------------------------------------------------------------------------

/// Input handles into the built circuit.
struct AstdeluxDiscreteInputs {
    explosion_vol: DataInputId,
    explosion_pitch: DataInputId,
    noise_reset: PulseInputId,
    thrust_en: LogicInputId,
    #[allow(dead_code)]
    mix: NodeId,
}

fn build_circuit() -> (DiscreteCircuit, AstdeluxDiscreteInputs) {
    let mut b = DiscreteCircuitBuilder::new(
        crate::atari_dvg::TIMING.cpu_clock_hz,
        phosphor_core::audio::host_sample_rate() as u64,
    );

    // The four EXPAUD lines as a code for R6, and the rate P7 leaves the LS74
    // clocked at, in hertz. Unscaled, because both are carried as themselves;
    // both start at zero, which is where RESET leaves F6 and so is silence.
    let explosion_vol = b.data_input("EXPLOSION_VOL", 1.0);
    let explosion_pitch = b.data_input("EXPLOSION_RATE", 1.0);
    let noise_reset = b.pulse_input("NOISE_RESET");
    let thrust_en = b.logic_input("THRUST_EN");

    let (_, expl_share, thrust_share) = mix_shares();

    // --- The noise generator, R8 and P8, which both paths take from. One
    // register, not two: the drawing has a single NOISE net leaving N4 and
    // reaching the 4016 for thrust and the LS74 for the explosion. ---
    let noise = b.custom(
        "NOISE",
        vec![noise_reset.into()],
        Box::new(NoiseGenerator::new()),
    );

    // --- Explosion: F6 latches volume and pitch, P7 divides the 12 kHz to clock
    // the LS74, and R6's four weighted resistors amplitude modulate what it
    // holds. "Noise is sampled at a frequency determined by P7, and control bits
    // EXPITCH0 and EXPITCH1 ... The noise is amplitude modulated in R6 by
    // EXPAUD0-EXPAUD3", in the drawing's own words. ---
    let expl_sampled = b.custom(
        "EXPLODE_SH",
        vec![noise, explosion_pitch.into()],
        Box::new(ExplosionSampleHold::new()),
    );
    let expl_dac = b.dac_weighted("EXPLODE_DAC", explosion_vol, &r6_weights());
    let expl_mod = b.multiply("EXPLODE_MOD", expl_sampled, expl_dac);
    let expl_lp = b.rc_low_pass("EXPLODE_LP", expl_mod, EXPLOSION_RC_R, EXPLOSION_RC_C);
    let expl = b.gain("EXPLODE", expl_lp, expl_share);

    // --- Thrust: "R8 and P8 generate random noise. This noise is filtered by
    // P11 and produces the rumble sound heard when the ship is thrusting." The
    // 4016 at R11 gates the same NOISE net on SHPTHRUSTEN, and P11 is the
    // band-pass and low-pass below. ---
    let thrust_rc = b.rc_low_pass("THRUST_RC", noise, THRUST_RC_R, THRUST_RC_C);
    // The 4016 gates ahead of the RC on the board rather than after it, so the
    // attack and release are shaped a little differently from this. Same
    // approximation the Asteroids path makes, and the same reason: it moves the
    // edges of the effect and nothing in the steady state.
    let thrust_gated = b.multiply("THRUST_GATE", thrust_rc, thrust_en);
    let thrust_bp = b.op_amp_band_pass(
        "THRUST_BP",
        thrust_gated,
        &[THRUST_BP_R_IN, THRUST_BP_R_REF],
        THRUST_BP_RF,
        THRUST_BP_C,
        THRUST_BP_C,
        0.0,
        -12.0,
        12.0,
    );
    let thrust_lp = b.rc_low_pass("THRUST_LP", thrust_bp, THRUST_LP_RF, THRUST_LP_C);
    // The band-pass concentrates the noise's energy by its Q, so dividing that
    // back out is what keeps the path's level a property of the mixer rather
    // than of the filter's sharpness.
    let thrust = b.gain(
        "THRUST",
        thrust_lp,
        THRUST_LP_GAIN * thrust_share * THRUST_Q / THRUST_BP_CENTER_GAIN,
    );

    let mix = b.add("MIX", &[expl, thrust]);
    b.output(mix, OutputGain::unity());

    let circuit = b.build();
    (
        circuit,
        AstdeluxDiscreteInputs {
            explosion_vol,
            explosion_pitch,
            noise_reset,
            thrust_en,
            mix,
        },
    )
}

// ---------------------------------------------------------------------------
// AsteroidsDeluxeDiscreteSound: board-facing wrapper
// ---------------------------------------------------------------------------

/// The board's thrust and explosion circuitry, driven by hardware intent.
#[derive(Saveable)]
#[save_version(1)]
#[save_tlv]
pub struct AsteroidsDeluxeDiscreteSound {
    #[save(id = 3)]
    circuit: DiscreteCircuit,
    /// Input handles, fixed when the circuit is built.
    #[save_skip]
    ids: AstdeluxDiscreteInputs,
    /// 0x3600: explosion volume on bits 2-5 and pitch on bits 6-7.
    #[save(id = 1)]
    explosion_reg: u8,
    /// 0x3C00-0x3C07, the M10 LS259. Only Q3 is a sound line on this board.
    #[save(id = 2)]
    audio_latch: u8,
}

impl AsteroidsDeluxeDiscreteSound {
    pub fn new() -> Self {
        let (circuit, ids) = build_circuit();
        Self {
            circuit,
            ids,
            explosion_reg: 0,
            audio_latch: 0,
        }
    }

    /// 0x3600: `Explosion volume` on D5-D2 and `Explosion pitch` on D7-D6, as
    /// the memory map names them. F6 latches all six.
    pub fn write_explosion(&mut self, data: u8) {
        self.explosion_reg = data;
        // The four EXPAUD lines as a code, EXPAUD0 (DB5) most significant. R6
        // turns it into a level; this hands over the code, not a fraction.
        self.circuit
            .set_data(self.ids.explosion_vol, f64::from((data >> 2) & 0x0F));
        // What P7 leaves the LS74 clocked at, in hertz.
        self.circuit.set_data(
            self.ids.explosion_pitch,
            NOISE_CLOCK_HZ / explosion_divider(data),
        );
    }

    /// 0x3C00-0x3C07: the addressable latch. `bit` selects the line.
    ///
    /// Q3 is `Ship thrust sound`. Q4 is the RAM bank select and the board reads
    /// it directly; the rest are start LEDs and coin counters. Only Q3 is a
    /// sound, which is why this takes the whole latch and acts on one line.
    pub fn write_audio_latch_bit(&mut self, bit: u8, value: bool) {
        crate::set_bit_active_high(&mut self.audio_latch, bit, value);
        if bit == 3 {
            self.circuit.set_logic(self.ids.thrust_en, value);
        }
    }

    /// 0x3E00: `Noise generator reset`, which clears the shift registers that
    /// both paths take their noise from.
    pub fn pulse_noise_reset(&mut self) {
        self.circuit.pulse(self.ids.noise_reset);
    }

    /// Advance the circuit by `board_cycles` of CPU-clock time.
    pub fn tick(&mut self, board_cycles: u64) {
        self.circuit.tick(board_cycles);
    }

    /// Drain produced mono `i16` samples. Returns the number written.
    pub fn fill_audio(&mut self, out: &mut [i16]) -> usize {
        self.circuit.fill_audio(out)
    }

    /// Output sample rate in Hz.
    pub fn sample_rate(&self) -> u32 {
        self.circuit.sample_rate()
    }

    /// The built circuit, for tooling that reads individual stages.
    pub fn circuit(&self) -> &DiscreteCircuit {
        &self.circuit
    }

    /// Whether thrust is currently enabled, for tests and the debug view.
    pub fn thrust_enabled(&self) -> bool {
        self.audio_latch & 0x08 != 0
    }

    pub fn reset(&mut self) {
        self.circuit.reset();
        self.explosion_reg = 0;
        self.audio_latch = 0;
    }
}

impl Default for AsteroidsDeluxeDiscreteSound {
    fn default() -> Self {
        Self::new()
    }
}

impl Debuggable for AsteroidsDeluxeDiscreteSound {
    fn debug_registers(&self) -> Vec<DebugRegister> {
        vec![
            DebugRegister {
                name: "EXPLOSION",
                value: self.explosion_reg as u64,
                width: 8,
            },
            DebugRegister {
                name: "EXPVOL",
                value: ((self.explosion_reg >> 2) & 0x0F) as u64,
                width: 8,
            },
            DebugRegister {
                name: "EXPPITCH",
                value: ((self.explosion_reg >> 6) & 0x03) as u64,
                width: 8,
            },
            DebugRegister {
                name: "THRUST",
                value: u64::from(self.thrust_enabled()),
                width: 8,
            },
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Run the circuit for a while and report the peak of what it produced.
    fn peak(sound: &mut AsteroidsDeluxeDiscreteSound, frames: usize) -> f64 {
        let mut buf = vec![0i16; 4096];
        let mut peak = 0i32;
        for _ in 0..frames {
            sound.tick(crate::atari_dvg::TIMING.cycles_per_frame());
            let n = sound.fill_audio(&mut buf);
            for &s in &buf[..n] {
                peak = peak.max((s as i32).abs());
            }
        }
        peak as f64 / 32767.0
    }

    /// Silence until something asks for a sound. A circuit that idles with noise
    /// on the output would be audible behind every frame of the game.
    #[test]
    fn nothing_enabled_is_silent() {
        let mut s = AsteroidsDeluxeDiscreteSound::new();
        assert!(peak(&mut s, 30) < 1e-3, "idle circuit is not silent");
    }

    /// The thrust line is latch bit 3, which is `Ship thrust sound` at 0x3C03 in
    /// the memory map. Being off by one here is silence, and it is exactly the
    /// bug this file was written to fix.
    #[test]
    fn latch_bit_three_is_thrust_and_no_other_bit_is() {
        for bit in 0..8u8 {
            let mut s = AsteroidsDeluxeDiscreteSound::new();
            s.write_audio_latch_bit(bit, true);
            let loud = peak(&mut s, 40) > 1e-3;
            assert_eq!(
                loud,
                bit == 3,
                "latch bit {bit}: {} sound",
                if loud { "made" } else { "made no" }
            );
        }
    }

    /// Thrust rumbles while it is held and stops when it is released.
    #[test]
    fn thrust_stops_when_the_button_is_released() {
        let mut s = AsteroidsDeluxeDiscreteSound::new();
        s.write_audio_latch_bit(3, true);
        assert!(peak(&mut s, 40) > 1e-3, "thrust made no sound");
        s.write_audio_latch_bit(3, false);
        // Past the band-pass ringing down at its own Q.
        peak(&mut s, 40);
        assert!(peak(&mut s, 20) < 1e-3, "thrust did not stop");
    }

    /// 0x3600's volume field reaches the output, so an explosion is loud where
    /// the game asks for loud. Volume is bits 2-5, which is what makes 0x3C the
    /// full-scale write and 0x00 silence.
    #[test]
    fn explosion_volume_scales_the_output() {
        let mut quiet = AsteroidsDeluxeDiscreteSound::new();
        quiet.write_explosion(0x04); // volume 1 of 15
        let quiet_peak = peak(&mut quiet, 40);

        let mut loud = AsteroidsDeluxeDiscreteSound::new();
        loud.write_explosion(0x3C); // volume 15 of 15
        let loud_peak = peak(&mut loud, 40);

        assert!(loud_peak > 1e-3, "full-volume explosion is silent");
        assert!(
            loud_peak > quiet_peak * 4.0,
            "volume did not scale: {quiet_peak} against {loud_peak}"
        );

        let mut off = AsteroidsDeluxeDiscreteSound::new();
        off.write_explosion(0x00);
        assert!(peak(&mut off, 40) < 1e-3, "zero volume is not silent");
    }

    /// The pitch field picks the noise's re-clock divider, so it has to change
    /// what comes out rather than only the volume.
    #[test]
    fn explosion_pitch_changes_the_sound() {
        let render = |reg: u8| {
            let mut s = AsteroidsDeluxeDiscreteSound::new();
            s.write_explosion(reg);
            let mut buf = vec![0i16; 4096];
            let mut out = Vec::new();
            for _ in 0..8 {
                s.tick(crate::atari_dvg::TIMING.cycles_per_frame());
                let n = s.fill_audio(&mut buf);
                out.extend_from_slice(&buf[..n]);
            }
            out
        };
        // Same volume, the two extreme pitch codes.
        let slow = render(0x3C); // divider 12
        let fast = render(0xBC); // divider 3
        assert_ne!(slow, fast, "pitch code did not change the waveform");
    }

    /// The board wants thrust the louder of the two, because R158 3.3k is a
    /// smaller summing resistor than the explosion's R85 4.7k. That is the one
    /// mixer fact that differs from Asteroids, so it is worth an assertion.
    #[test]
    fn thrust_is_weighted_above_explosion_as_the_summing_resistors_say() {
        let (_, expl, thrust) = mix_shares();
        let ratio = thrust / expl;
        assert!(
            (ratio - R_EXPLOSION / R_THRUST).abs() < 1e-9,
            "mixer ratio {ratio} is not the resistor ratio"
        );
        assert!(
            ratio > 1.42 && ratio < 1.43,
            "expected about 1.424, got {ratio}"
        );
    }

    /// The three shares are a partition, so everything at once cannot clip.
    #[test]
    fn the_mixer_shares_sum_to_one() {
        let (p, e, t) = mix_shares();
        assert!((p + e + t - 1.0).abs() < 1e-12);
        assert!((POKEY_MIX_SHARE - p).abs() < 1e-12);
        assert!(p > 0.0 && e > 0.0 && t > 0.0);
    }

    /// The four gates on P7's load inputs give 12, 6, 3 and 5.
    ///
    /// Those four numbers are the whole of the explosion's pitch, and written as
    /// a table they look arbitrary enough to be worth pinning against the gates
    /// that actually produce them. A transposed pair here is an explosion at the
    /// wrong pitch and nothing else, which is not a failure anything else would
    /// catch.
    #[test]
    fn the_pitch_gates_divide_by_twelve_six_three_and_five() {
        // Code in bits 7-6, with the volume bits set so the write is realistic.
        for (code, want) in [(0x00, 12.0), (0x40, 6.0), (0x80, 3.0), (0xC0, 5.0)] {
            let got = explosion_divider(code | 0x3C);
            assert_eq!(got, want, "pitch code {code:#04x}");
        }
    }

    /// R6 is four preferred values, not a binary ladder, so its steps are
    /// slightly uneven and the top bit is worth a little over half.
    ///
    /// Modeling the volume as `code / 15` would be smooth where the board is
    /// not. The numbers are small, which is exactly why a test is the only thing
    /// that would notice someone "simplifying" it back.
    #[test]
    fn r6_is_not_quite_a_binary_ladder() {
        let w = r6_weights();
        assert_eq!(w.len(), 4);
        let total: f64 = w.iter().sum();
        assert!(
            (total - 1.0).abs() < 1e-12,
            "weights should reach full scale"
        );

        // Bit 0 is EXPAUD3 through the largest resistor; bit 3 is EXPAUD0
        // through the smallest.
        assert!(w[3] > w[2] && w[2] > w[1] && w[1] > w[0], "not monotonic");
        assert!(
            (w[3] - 0.5435).abs() < 5e-4,
            "top bit is {} , expected about 0.5435",
            w[3]
        );
        // A true ladder would put it at exactly 8/15.
        assert!(
            (w[3] - 8.0 / 15.0).abs() > 5e-3,
            "top bit came out binary, so the preferred values were lost"
        );
    }

    /// NOISERESET clears both LS164s, and an XNOR chain carries on out of
    /// all-zeroes rather than locking up. If it locked, the strobe would silence
    /// the board until the next power cycle.
    #[test]
    fn the_noise_reset_clears_the_registers_without_stopping_them() {
        let mut s = AsteroidsDeluxeDiscreteSound::new();
        s.write_audio_latch_bit(3, true);
        assert!(
            peak(&mut s, 40) > 1e-3,
            "thrust made no sound to begin with"
        );
        s.pulse_noise_reset();
        assert!(
            peak(&mut s, 40) > 1e-3,
            "the noise stopped after a reset, so the register locked"
        );
    }

    /// Both paths take the same NOISE net, which is what the drawing has: one
    /// generator, gated for thrust and sampled for the explosion. Resetting it
    /// has to be visible to both, and that is the cheapest way to show they are
    /// not two independent sources.
    #[test]
    fn one_generator_feeds_both_paths() {
        let render = |reset_at: Option<usize>| {
            let mut s = AsteroidsDeluxeDiscreteSound::new();
            s.write_audio_latch_bit(3, true);
            s.write_explosion(0x3C);
            let mut buf = vec![0i16; 4096];
            let mut out = Vec::new();
            for f in 0..8 {
                if Some(f) == reset_at {
                    s.pulse_noise_reset();
                }
                s.tick(crate::atari_dvg::TIMING.cycles_per_frame());
                let n = s.fill_audio(&mut buf);
                out.extend_from_slice(&buf[..n]);
            }
            out
        };
        assert_ne!(
            render(None),
            render(Some(2)),
            "clearing the shared register changed nothing"
        );
    }

    /// A reset leaves nothing sounding, including a thrust that was held.
    #[test]
    fn reset_silences_a_held_thrust() {
        let mut s = AsteroidsDeluxeDiscreteSound::new();
        s.write_audio_latch_bit(3, true);
        s.write_explosion(0x3C);
        assert!(peak(&mut s, 20) > 1e-3);
        s.reset();
        assert!(!s.thrust_enabled());
        assert!(peak(&mut s, 20) < 1e-3, "reset left the circuit sounding");
    }
}
