//! Debug inspection traits for interactive debugging of emulated machines.
//!
//! Three layers:
//! - `Debuggable` — any device that can present its register state
//! - `DebugCpu` — CPU-specific capabilities (extends Debuggable)
//! - `BusDebug` — bus-level discovery of all devices and CPUs

use crate::core::memory_map::{DebugRead, MemoryMap, WatchpointHit, WatchpointKind};
use crate::cpu::disasm::DisassembledInstruction;

/// A single CPU register for display in the debug panel.
pub struct DebugRegister {
    /// Register name (e.g., "A", "PC", "SP").
    pub name: &'static str,
    /// Register value (all register widths fit in u64).
    pub value: u64,
    /// Display width in bits (8 or 16).
    pub width: u8,
}

/// Result of disassembling one instruction at a given address.
pub struct DebugDisassembly {
    /// Address of the instruction.
    pub addr: u32,
    /// Raw instruction bytes.
    pub bytes: Vec<u8>,
    /// Formatted instruction text (e.g., "LDA  #$42").
    pub text: String,
    /// Total byte length of the instruction.
    pub byte_len: u8,
}

/// Any hardware device that can present its state for debug inspection.
///
/// Implemented by CPUs, PIAs, blitters, DACs, and other peripherals.
/// The debugger uses this to display device register panels.
pub trait Debuggable {
    /// Get all registers for display.
    fn debug_registers(&self) -> Vec<DebugRegister>;
}

/// CPU-specific debug capabilities (extends Debuggable).
///
/// Provides program counter access, instruction boundary detection,
/// and disassembly. The debugger uses this for stepping and code display.
pub trait DebugCpu: Debuggable {
    /// Read the current program counter.
    ///
    /// `u32` so 24/32-bit CPUs (M68000) report their full PC; 16-bit CPUs
    /// widen losslessly.
    fn debug_pc(&self) -> u32;

    /// True if the CPU is at an instruction boundary (ready to fetch next opcode).
    fn debug_at_instruction_boundary(&self) -> bool;

    /// Disassemble one instruction from raw bytes at the given address.
    ///
    /// 16-bit CPUs decode `addr` modulo their 64 KB space; their debuggers
    /// never pass addresses above `0xFFFF`.
    fn debug_disassemble(&self, addr: u32, bytes: &[u8]) -> DisassembledInstruction;
}

/// Debug view of a bus and its connected devices.
///
/// The debugger interrogates the bus to discover CPUs and peripherals.
/// Generated by `#[derive(BusDebug)]` on board/system structs.
pub trait BusDebug {
    /// All devices connected to this bus, with contextual names.
    /// CPUs appear here too (they implement Debuggable).
    fn devices(&self) -> Vec<(&str, &dyn Debuggable)>;

    /// CPUs on this bus (for stepping and disassembly).
    fn cpus(&self) -> Vec<(&str, &dyn DebugCpu)>;

    /// Side-effect-free memory read from a CPU's address space.
    /// Returns `None` for unmapped or I/O addresses.
    fn read(&self, cpu_index: usize, addr: u16) -> Option<u8>;

    /// Debug memory write into a CPU's address space.
    fn write(&mut self, cpu_index: usize, addr: u16, data: u8);

    /// Side-effect-free memory read with full address semantics: backed
    /// memory (value returned), mapped I/O (reading the live device would
    /// have side effects), or unmapped.
    ///
    /// The default routes through [`read`](Self::read), which cannot
    /// distinguish I/O from unmapped — both report `Unmapped`.
    /// `#[derive(BusDebug)]` overrides this with per-map semantics via
    /// `AddressSpace16::debug_peek`.
    fn peek(&self, cpu_index: usize, addr: u32) -> DebugRead {
        if addr > 0xFFFF {
            return DebugRead::Unmapped;
        }
        match self.read(cpu_index, addr as u16) {
            Some(value) => DebugRead::Backed {
                value: value as u32,
                width: 1,
                region_id: 0,
            },
            None => DebugRead::Unmapped,
        }
    }

    /// Write to a device register by device index and register offset.
    /// Device indices match the order returned by `devices()`.
    /// Only `#[debug_device]` fields respond; CPU indices are ignored.
    fn write_device_register(&mut self, _device_index: usize, _offset: u16, _data: u8) {}

    /// Reset an individual device by index.
    /// Device indices match the order returned by `devices()`.
    fn reset_device(&mut self, _device_index: usize) {}

    // --- Watchpoint methods (generated by `#[debug_map]` in derive) ---

    /// Consume a pending watchpoint hit from any address space.
    fn take_watchpoint_hit(&mut self) -> Option<WatchpointHit> {
        None
    }

    /// Set a memory watchpoint in the address space of `cpu_index`.
    fn set_watchpoint(&mut self, _cpu_index: usize, _addr: u16, _kind: WatchpointKind) {}

    /// Clear a memory watchpoint in the address space of `cpu_index`.
    fn clear_watchpoint(&mut self, _cpu_index: usize, _addr: u16, _kind: WatchpointKind) {}

    /// Clear all memory watchpoints across all address spaces.
    fn clear_all_watchpoints(&mut self) {}

    /// Get the memory map for a CPU's address space (for region introspection).
    fn memory_map(&self, _cpu_index: usize) -> Option<&MemoryMap> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Manual `BusDebug` with only `read`/`write`, exercising the default
    /// `peek`: backed bytes report `Backed`, everything else `Unmapped`
    /// (the default cannot distinguish I/O).
    struct ReadOnlyBus;

    impl BusDebug for ReadOnlyBus {
        fn devices(&self) -> Vec<(&str, &dyn Debuggable)> {
            Vec::new()
        }
        fn cpus(&self) -> Vec<(&str, &dyn DebugCpu)> {
            Vec::new()
        }
        fn read(&self, _cpu_index: usize, addr: u16) -> Option<u8> {
            (addr < 0x8000).then_some(addr as u8)
        }
        fn write(&mut self, _cpu_index: usize, _addr: u16, _data: u8) {}
    }

    #[test]
    fn default_peek_routes_through_read() {
        let bus = ReadOnlyBus;
        assert_eq!(
            bus.peek(0, 0x1234),
            DebugRead::Backed {
                value: 0x34,
                width: 1,
                region_id: 0
            }
        );
        assert_eq!(bus.peek(0, 0x9000), DebugRead::Unmapped);
        // Out of 16-bit range: unmapped until the debug surface widens
        assert_eq!(bus.peek(0, 0x1_0000), DebugRead::Unmapped);
    }
}
